version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Don't map location outside container to inside
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # Don't map location outside container to inside
      - .:/app
    command: ["npm", "run", "test"] # Override default CMD in dockerfile.dev

